name: CantHideStaff
version: ${project.version}
main: com.vendoau.canthidestaff.CantHideStaff
api-version: 1.16

description: Prevent chat messages from staff members being hidden
author: VendoAU

permissions:
  canthidestaff.staff:
    description: Messages from players that have this permission can't be hidden
